### ISSUE TITLE
Nothing is showed

### ISSUE THREAD

**Issue by jempo** [marcomow/ble-bulb-card#1]
Hi @marcomow, thank you very much for this front-end integration, i was expecting this from many years :).

Installing from HACS, when i click to connection BLE button, this doesn't show me anything. I've followed the instruction in the README's project but i don't know if somethings is wrong.
I've checked in HA logs and in the JS console but nothing. There is some any settings that i need to enable in the browser or in HA?
Many thanks.

**Comment by marcomow** [comment]
Hi @jempo, can you please specify the device and browser you are using? 
Also, could you please try with other devices and browsers?

**Comment by jempo** [comment]
Sure! i'm using macmini with chrome 87.0.4280.67
i've try to use also the companion iOS App but the card is not showed

**Comment by marcomow** [comment]
Hi @jempo, can you share the configuration of your card?

**Comment by MattiaTomasi** [comment]
Hi  @marcomow , really good idea and project! But same problem for me, I'm using pi4 with hass.io. Installed with HACS. When I click the button in the card for search new devices nothing happen, I've already enabled the ble tracker in the configuration and the triones light is present.
The same thing using android mobile app or different browser (in this moment I'm using Chrome)

**Comment by jempo** [comment]
Hi @marcomow, sorry for my delay. Here the code in to lovelance

`type: 'custom:ble-bulb-card'
bulb-types:
  - triones
`

**Comment by marcomow** [comment]
Hey @jempo @MattiaTomasi can you please check if web bluetooth is working https://googlechrome.github.io/samples/web-bluetooth/device-info.html?allDevices=true, please open this link, check "All devices" and click "Get Bluetooth Device info" and see if the bluetooth window is opening.

On the android app I checked and it is not working, I have to think about how to solve it.

**Comment by jempo** [comment]
Hi @marcomow , i've done a test with the link and i've the output in screenshot.
![Schermata 2020-12-01 alle 14 49 13](https://user-images.githubusercontent.com/5411098/100749121-83b26a00-33e4-11eb-8c54-5096597bf48a.png)

It could be a problem that i don't use HA with HTTPS (http://<ip>:8123)?

**Comment by marcomow** [comment]
Yes @jempo, that's exactly the issue. Web bluetooth is accessible only with HTTPS connections. I'll place a disclaimer in the readme.

As a solution I warmly recommend @PhrantiK's [letsdnscloud add-on](https://github.com/PhrantiK/hassio-addons) that you can use with your custom domain, or the [classic DuckDNS solution](https://techtechandmoretech.com/guides/hass-duckdns/) . 

@MattiaTomasi please let me know if that's the case also for you.

**Comment by MattiaTomasi** [comment]
Hi @marcomow , I tried, it was exactly that. Using https it work correctly! thank you

**Comment by marcomow** [comment]
Good to know @MattiaTomasi, and thanks for the feedback - feel free to provide more if you like. 

I'll close the issue then.
