### ISSUE TITLE
Can't save card

### ISSUE THREAD

**Issue by IncByteLC** [marcomow/ble-bulb-card#2]
I was able to pair light, can switch it on or off, but SAVE button is not active and unable to save the card.

**Comment by marcomow** [comment]
Hi,

Try to add or remove new lines in the card, if you wrote everything
correctly the button should show up.

Please let me know if it works

**Comment by IncByteLC** [comment]
It helps!
Thx.

Sad that there are no options for automation or stable connection without scanning all the time.
But at least it works, my first device connected.
