### ISSUE TITLE
is there a way to better integrate in ha?

### ISSUE THREAD

**Issue by FrancYescO** [marcomow/ble-bulb-card#3]
sorry for opening an issue because is probably out of scope, but as basically this is just a browser controller for this bulbs, do you know any way that can allow us to integrate these BLE lights as entities in home assistant?

**Comment by marcomow** [comment]
yes, this is just a simple controller card.
What you're looking for may be achieved using a bridge device, f.i. using ESPhome, take a look here https://esphome.io/components/esp32_ble_tracker.html
